/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleUI_include_h__
#define _MulleUI_include_h__

// How to tweak the following glfw #include
//    remove:             `mulle-sourcetree mark glfw no-header`
//    rename:             `mulle-sde dependency|library set glfw include whatever.h`
//    toggle #import:     `mulle-sourcetree mark glfw [no-]import`
//    toggle public:      `mulle-sourcetree mark glfw [no-]public`
//    toggle optional:    `mulle-sourcetree mark glfw [no-]require`
//    remove for os:      `mulle-sourcetree mark glfw no-os-<osname>`
# include <GLFW/glfw3.h>   // glfw

// How to tweak the following mulle-testallocator #include
//    remove:             `mulle-sourcetree mark mulle-testallocator no-header`
//    rename:             `mulle-sde dependency|library set mulle-testallocator include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-testallocator [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-testallocator [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-testallocator [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-testallocator no-os-<osname>`
# include <mulle-testallocator/mulle-testallocator.h>   // mulle-testallocator

#endif
