/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_MATCH_TO_C_OBJC_HEADERS_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_MATCH_TO_C_RUN DISABLE
 */
