/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleUI_include_private_h__
#define _MulleUI_include_private_h__

// How to tweak the following mujs #include
//    remove:             `mulle-sourcetree mark mujs no-header`
//    rename:             `mulle-sde dependency|library set mujs include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mujs [no-]import`
//    toggle public:      `mulle-sourcetree mark mujs [no-]public`
//    toggle optional:    `mulle-sourcetree mark mujs [no-]require`
//    remove for os:      `mulle-sourcetree mark mujs no-os-<osname>`
# include <mujs.h>   // mujs

#endif
