/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleUI_import_h__
#define _MulleUI_import_h__

// How to tweak the following MulleJS #import
//    remove:             `mulle-sourcetree mark MulleJS no-header`
//    rename:             `mulle-sde dependency|library set MulleJS include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleJS [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleJS [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleJS [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleJS [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleJS no-os-<osname>`
# if defined( __has_include) && __has_include("MulleJS.h")
#   import "MulleJS.h"   // MulleJS
# else
#   import <MulleJS/MulleJS.h>   // MulleJS
# endif

// How to tweak the following Foundation #import
//    remove:             `mulle-sourcetree mark Foundation no-header`
//    rename:             `mulle-sde dependency|library set Foundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark Foundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark Foundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark Foundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark Foundation [no-]require`
//    remove for os:      `mulle-sourcetree mark Foundation no-os-<osname>`
# if defined( __has_include) && __has_include("Foundation.h")
#   import "Foundation.h"   // Foundation
# else
#   import <Foundation/Foundation.h>   // Foundation
# endif

// How to tweak the following MulleObjCBase64Foundation #import
//    remove:             `mulle-sourcetree mark MulleObjCBase64Foundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCBase64Foundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCBase64Foundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCBase64Foundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCBase64Foundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCBase64Foundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCBase64Foundation no-os-<osname>`
# if defined( __has_include) && __has_include("MulleObjCBase64Foundation.h")
#   import "MulleObjCBase64Foundation.h"   // MulleObjCBase64Foundation
# else
#   import <MulleObjCBase64Foundation/MulleObjCBase64Foundation.h>   // MulleObjCBase64Foundation
# endif

#ifdef __has_include
# if __has_include( "_MulleUI-include.h")
#  include "_MulleUI-include.h"
# endif
#endif


#endif
