/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleUI_import_h__
#define _MulleUI_import_h__

// How to tweak the following glfw #include
//    remove:             `mulle-sourcetree mark glfw no-header`
//    rename:             `mulle-sde dependency|library set glfw include whatever.h`
//    toggle #import:     `mulle-sourcetree mark glfw [no-]import`
//    toggle public:      `mulle-sourcetree mark glfw [no-]public`
//    toggle optional:    `mulle-sourcetree mark glfw [no-]require`
//    remove for os:      `mulle-sourcetree mark glfw no-os-<osname>`
# include <GLFW/glfw3.h>   // glfw

// How to tweak the following mulle-testallocator #include
//    remove:             `mulle-sourcetree mark mulle-testallocator no-header`
//    rename:             `mulle-sde dependency|library set mulle-testallocator include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-testallocator [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-testallocator [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-testallocator [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-testallocator no-os-<osname>`
# include <mulle-testallocator/mulle-testallocator.h>   // mulle-testallocator

// How to tweak the following MulleJS #import
//    remove:             `mulle-sourcetree mark MulleJS no-header`
//    rename:             `mulle-sde dependency|library set MulleJS include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleJS [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleJS [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleJS [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleJS no-os-<osname>`
# import <MulleJS/MulleJS.h>   // MulleJS

// How to tweak the following Foundation #import
//    remove:             `mulle-sourcetree mark Foundation no-header`
//    rename:             `mulle-sde dependency|library set Foundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark Foundation [no-]import`
//    toggle public:      `mulle-sourcetree mark Foundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark Foundation [no-]require`
//    remove for os:      `mulle-sourcetree mark Foundation no-os-<osname>`
# import <Foundation/Foundation.h>   // Foundation

// How to tweak the following MulleBase64 #import
//    remove:             `mulle-sourcetree mark MulleBase64 no-header`
//    rename:             `mulle-sde dependency|library set MulleBase64 include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleBase64 [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleBase64 [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleBase64 [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleBase64 no-os-<osname>`
# import <MulleBase64/MulleBase64.h>   // MulleBase64

#endif
