/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_gl_example_include_h__
#define _mulle_gl_example_include_h__

# include <libdill.h>   // libdill

# include <GLFW/glfw3.h>   // glfw

#endif
