/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_gl_example_import_h__
#define _mulle_gl_example_import_h__

# import <MulleObjC/MulleObjC.h>   // MulleObjC

# import <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

#endif
