/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleg_lexample_import_private_h__
#define _mulleg_lexample_import_private_h__

/* no headers */

#endif
