/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_ui_kit_import_h__
#define _mulle_ui_kit_import_h__

// How to tweak the following Foundation #import
//    remove:        `mulle-sourcetree mark Foundation no-header`
//    rename:        `mulle-sourcetree mark Foundation set include whatever.h`
//    make private:  `mulle-sourcetree mark Foundation no-public`
//    make public:   `mulle-sourcetree mark Foundation public`
//    make optional: `mulle-sourcetree mark Foundation no-require`
//    remove for os: `mulle-sourcetree mark Foundation no-os-<osname>`
# import <Foundation/Foundation.h>   // Foundation

#include "_MulleUIKit-include.h"


#endif
