/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*/

#ifndef _mulle_gl_example_import_h__
#define _mulle_gl_example_import_h__

// remove with `mulle-sourcetree mark MulleObjC no-header`
// rename with `mulle-sourcetree mark MulleObjC set include whatever.h`
# import <MulleObjC/MulleObjC.h>   // MulleObjC

// remove with `mulle-sourcetree mark mulle-objc-compat no-header`
// rename with `mulle-sourcetree mark mulle-objc-compat set include whatever.h`
# import <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

#endif
