#ifndef mulleg_lexample_include_h__
#define mulleg_lexample_include_h__

/* This is a central include file to keep dependencies out of the library
   C files. It is usally included by .h files only.

   The advantage is that now .c and .h files become motile. They can
   be moved to other projects and don't need to be edited. Also less typing...

   Therefore it is important that this file is called "include.h" and
   not "MulleGLExample-include.h" to keep the #include statements in the
   library code uniform.

   The C-compiler will pick up the nearest one.
*/

// needed for libdill
#ifndef _POSIX_SOURCE
# define _POSIX_SOURCE
#endif

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */
#include "_MulleUI-include.h"

/* You can add some more include statements here */

#include "version.h"

#endif
