#ifndef mulle_gl_example_include_private_h__
#define mulle_gl_example_include_private_h__


/* DO:    #include this files in sources

   DONT:  #include this files in headers
          #import this file anywhere (except in import-private.h)
 */

#define MULLE_UI_GL      1
#define MULLE_UI_GLES2   2
#define MULLE_UI_GLES3   3
//#define MULLE_UI_VULKAN  4

// change the "backend" to use
#define MULLE_UI_GLVERSION   MULLE_UI_GL

#if MULLE_UI_GLVERSION == MULLE_UI_GLES2
# define GLFW_INCLUDE_ES2
# ifdef DEFINE_NANOVG_GL_IMPLEMENTATION
#  define NANOVG_GLES2_IMPLEMENTATION
# endif
#endif

#if MULLE_UI_GLVERSION == MULLE_UI_GLES3
# define GLFW_INCLUDE_ES3
# ifdef DEFINE_NANOVG_GL_IMPLEMENTATION
#  define NANOVG_GLES3_IMPLEMENTATION
# endif
#endif

#if MULLE_UI_GLVERSION == MULLE_UI_GL
// GLFW_INCLUDE_... keep undefined for OpenGL3
// see: https://www.glfw.org/docs/latest/build_guide.html
# ifdef DEFINE_NANOVG_GL_IMPLEMENTATION
#  define NANOVG_GL3_IMPLEMENTATION
# endif
#endif


#include "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#include "_MulleUI-include-private.h"

/* You can add some more include statements here */

#include "nanovg.h"
#include "nanovg_gl.h"
#include "nanovg_gl_utils.h"
#include "nanosvg.h"


#endif
