#ifndef mulle_gl_example_include_private_h__
#define mulle_gl_example_include_private_h__


/* DO:    #include this files in sources

   DONT:  #include this files in headers
          #import this file anywhere (except in import-private.h)
 */

// keep undefined for OpenGL3
// see: https://www.glfw.org/docs/latest/build_guide.html
#define GLFW_INCLUDE_ES2       // GLES2

/* This is a central include file to not expose includes to consumers of
   this library. It must not be imported by .h files, but by .c files
   only.
 */

#include "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#include "_MulleUIKit-include-private.h"

/* You can add some more include statements here */

#include "nanovg.h"
#include "nanovg_gl.h"
#include "nanovg_gl_utils.h"
#include "nanosvg.h"


#endif
