#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
nanosvg/src
nanovg/src
src
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
nanosvg/src/nanosvg.h
nanosvg/src/nanosvgrast.h
nanovg/src/fontstash.h
nanovg/src/nanovg_gl.h
nanovg/src/nanovg_gl_utils.h
nanovg/src/nanovg.h
nanovg/src/stb_image.h
nanovg/src/stb_truetype.h
src/CALayer.h
src/CGAffineTransform.h
src/CGBase.h
src/CGContext.h
src/CGFont.h
src/CGGeometry+CString.h
src/CGGeometry.h
src/Ghostscript_Tiger-svg.inc
src/MulleBitmapImage.h
src/MulleCheckboxLayer.h
src/MulleImageLayer.h
src/MulleSVGImage.h
src/MulleSVGLayer.h
src/MulleScrollIndicatorView.h
src/MulleSegmentedControlLayer.h
src/MulleSliderLayer.h
src/MulleStepperLayer.h
src/MulleTextLayer.h
src/MulleTextureImage.h
src/MulleTrackingArea.h
src/Roboto-Regular.inc
src/UIApplication.h
src/UIButton.h
src/UIControl.h
src/UIEdgeInsets+CString.h
src/UIEdgeInsets.h
src/UIEvent.h
src/UIImage.h
src/UILabel.h
src/UIResponder.h
src/UIScrollView.h
src/UISegmentedControl.h
src/UISlider.h
src/UIStepper.h
src/UISwitch.h
src/UIView+CGGeometry.h
src/UIView+UIEvent.h
src/UIView+UIResponder.h
src/UIView.h
src/UIWindow+UIResponder.h
src/UIWindow.h
src/anonymous-pro.inc
src/bmp-writer.h
src/entypo.inc
src/import.h
src/include.h
src/mulle-pointerarray+ObjC.h
src/mulle-quadtree.h
src/mulle-timespec.h
src/nanoperf.h
src/nanovg+CString.h
src/sealie-bitmap.inc
src/tiger-svg.inc
src/turtle-bitmap.inc
src/version.h
src/viech-bitmap.inc
)

