#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
nanovg/src
src
) 

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
nanovg/src/fontstash.h
nanovg/src/nanovg_gl.h
nanovg/src/nanovg_gl_utils.h
nanovg/src/nanovg.h
nanovg/src/stb_image.h
nanovg/src/stb_truetype.h
src/import.h
src/include.h
src/version.h
) 

