#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
nanovg/src/nanovg.c
src/CAAnimation.m
src/CALayer.m
src/CGAffineTransform.c
src/CGContext.m
src/CGFont.m
src/CGGeometry+CString.m
src/CGGeometry.c
src/MulleBitmapImage.m
src/MulleCheckboxLayer.m
src/MulleImageLayer.m
src/MulleSVGImage.m
src/MulleSVGLayer.m
src/MulleScrollIndicatorView.m
src/MulleSegmentedControlLayer.m
src/MulleSliderLayer.m
src/MulleStepperLayer.m
src/MulleTextLayer.m
src/MulleTextureImage.m
src/MulleTrackingArea.m
src/UIApplication.m
src/UIButton.m
src/UIControl.m
src/UIEdgeInsets+CString.m
src/UIEdgeInsets.c
src/UIEvent.m
src/UIImage.m
src/UILabel.m
src/UIResponder.m
src/UIScrollView.m
src/UISegmentedControl.m
src/UISlider.m
src/UIStepper.m
src/UISwitch.m
src/UIView+CGGeometry.m
src/UIView+UIEvent.m
src/UIView+UIResponder.m
src/UIView.m
src/UIWindow+UIResponder.m
src/UIWindow.m
src/bmp-writer.c
src/main.m
src/mulle-pointerarray+ObjC.m
src/mulle-quadtree.m
src/nanoperf.m
src/nanosvg.m
src/nanovg+CString.m
)
