#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
nanovg/src/nanovg.c
src/CALayer.m
src/CGContext.m
src/CGGeometry.c
src/MulleBitmapImage.m
src/MulleBitmapLayer.m
src/MulleSVGImage.m
src/MulleSVGLayer.m
src/UIApplication.m
src/UIButton.m
src/UIEvent.m
src/UIView+UIEvent.m
src/UIView.m
src/UIWindow.m
src/main.m
src/nanosvg.m
)
